/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nathan
 */
public class BolocoMenu extends javax.swing.JFrame {

    /**
     * Creates new form BolocoMenu
     */
    public BolocoMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        BurritoBowlTypeButtonGroup = new javax.swing.ButtonGroup();
        BurritoBowlFillWithButtonGroup = new javax.swing.ButtonGroup();
        BurritoBowlSizeButtonGroup = new javax.swing.ButtonGroup();
        BurritoBowlExtraButtonGroup = new javax.swing.ButtonGroup();
        SaladTypeButtonGroup = new javax.swing.ButtonGroup();
        ShakeTypeButtonGroup = new javax.swing.ButtonGroup();
        ShakeSizeButtonGroup = new javax.swing.ButtonGroup();
        OtherSidesButtonGroup = new javax.swing.ButtonGroup();
        OtherDessertButtonGroup = new javax.swing.ButtonGroup();
        OtherDrinkButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        MenuItemsTabbedPannel = new javax.swing.JTabbedPane();
        BurritosBowlsPannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GolocoBurrioBowlRadioButton = new javax.swing.JRadioButton();
        TheSummerBurrioBowlRadioButton = new javax.swing.JRadioButton();
        JakunBurriotBowlRadioButton = new javax.swing.JRadioButton();
        ClassicMexcianBurriotBowlRadioButton = new javax.swing.JRadioButton();
        TikkaMasalaBurriotBowlRadioButton = new javax.swing.JRadioButton();
        BurriotBowlTeriyakiRadioButton = new javax.swing.JRadioButton();
        BurritoBowlBuffaloRadioButton = new javax.swing.JRadioButton();
        FillWithFreshFajitaVegetablesRadioButton = new javax.swing.JRadioButton();
        FillWithPorkCarnitasRadioButton = new javax.swing.JRadioButton();
        FillWithGrassFedSteakRadioButton = new javax.swing.JRadioButton();
        FillWithWhiteMeatChickenRadioButton = new javax.swing.JRadioButton();
        FillWithDarkMeatChickenRadioButton = new javax.swing.JRadioButton();
        FillWithOrganicTofuRadioButton = new javax.swing.JRadioButton();
        GuacExtraSourCreamCheckbox = new javax.swing.JCheckBox();
        SourCreamExtraCheckBox = new javax.swing.JCheckBox();
        BurrioBowlSizeComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CesarSaladRadioButton = new javax.swing.JRadioButton();
        MedeteranianSaladRadioButton = new javax.swing.JRadioButton();
        NewEnglandHarvestSaladRadioButton = new javax.swing.JRadioButton();
        CharredBroccoliSaladRadioButton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NutellaMilkshakeShakeRadioButton = new javax.swing.JRadioButton();
        JimmyCarterShakeRadioButton = new javax.swing.JRadioButton();
        SoyBerryShakeRadioButton = new javax.swing.JRadioButton();
        TheMilkshakeRadioButton = new javax.swing.JRadioButton();
        TropiKaleShakeRadioButton = new javax.swing.JRadioButton();
        StrawbanaShakeRadioButton = new javax.swing.JRadioButton();
        BerryBlitzShakeRadioButton = new javax.swing.JRadioButton();
        MangoPassionShakeRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        SizeShakeComboBox = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ChipsAndGuacSideRadioButton = new javax.swing.JRadioButton();
        ChipsAndSalsaSideRadioButton = new javax.swing.JRadioButton();
        ChipsSideRadioButton = new javax.swing.JRadioButton();
        CookieDessertRadioButton = new javax.swing.JRadioButton();
        MiniCookieDessertRadioButton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CoffeeDrinkRadioButton = new javax.swing.JRadioButton();
        SodaDrinkRadioButton = new javax.swing.JRadioButton();
        BolocoImageLabel = new javax.swing.JLabel();
        RecepitCheckBox = new javax.swing.JCheckBox();
        AddTipCheckBox = new javax.swing.JCheckBox();
        HowManyLabel = new javax.swing.JLabel();
        HowManyTextField = new javax.swing.JTextField();
        OrderNowButton = new javax.swing.JButton();
        RestartButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        NewMenuItem = new javax.swing.JMenuItem();
        OpenMenuItem = new javax.swing.JMenuItem();
        SaveMenuItem = new javax.swing.JMenuItem();
        QuitMenuItem = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        SettingsMenuItem = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        AboutMenuItem = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boloco Menu");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        MenuItemsTabbedPannel.setToolTipText("");

        BurritosBowlsPannel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        BurritosBowlsPannel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Type");
        BurritosBowlsPannel.add(jLabel1);
        jLabel1.setBounds(23, 28, 50, 29);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Extra");
        BurritosBowlsPannel.add(jLabel2);
        jLabel2.setBounds(710, 30, 58, 29);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Fill With");
        BurritosBowlsPannel.add(jLabel3);
        jLabel3.setBounds(236, 28, 92, 29);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setText("Size");
        BurritosBowlsPannel.add(jLabel4);
        jLabel4.setBounds(489, 28, 43, 29);

        BurritoBowlTypeButtonGroup.add(GolocoBurrioBowlRadioButton);
        GolocoBurrioBowlRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        GolocoBurrioBowlRadioButton.setText("Goloco");
        GolocoBurrioBowlRadioButton.setToolTipText("Create Your Own Burrito");
        BurritosBowlsPannel.add(GolocoBurrioBowlRadioButton);
        GolocoBurrioBowlRadioButton.setBounds(23, 283, 91, 28);

        BurritoBowlTypeButtonGroup.add(TheSummerBurrioBowlRadioButton);
        TheSummerBurrioBowlRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        TheSummerBurrioBowlRadioButton.setText("The Summer");
        TheSummerBurrioBowlRadioButton.setToolTipText("Mango Salsa, Melted Cheese, Black Beans, Boloco Rice");
        TheSummerBurrioBowlRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheSummerBurrioBowlRadioButtonActionPerformed(evt);
            }
        });
        BurritosBowlsPannel.add(TheSummerBurrioBowlRadioButton);
        TheSummerBurrioBowlRadioButton.setBounds(23, 249, 142, 28);

        BurritoBowlTypeButtonGroup.add(JakunBurriotBowlRadioButton);
        JakunBurriotBowlRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        JakunBurriotBowlRadioButton.setText("Cajun");
        JakunBurriotBowlRadioButton.setToolTipText("Roasted Corn Salsa, Creole Sour Cream, Black Beans, Boloco Rice");
        BurritosBowlsPannel.add(JakunBurriotBowlRadioButton);
        JakunBurriotBowlRadioButton.setBounds(23, 215, 78, 28);

        BurritoBowlTypeButtonGroup.add(ClassicMexcianBurriotBowlRadioButton);
        ClassicMexcianBurriotBowlRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        ClassicMexcianBurriotBowlRadioButton.setText("Classic Mexican");
        ClassicMexcianBurriotBowlRadioButton.setToolTipText("Tomato Salsa, Cilantro, Melted Cheese, Pinto Beans");
        ClassicMexcianBurriotBowlRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassicMexcianBurriotBowlRadioButtonActionPerformed(evt);
            }
        });
        BurritosBowlsPannel.add(ClassicMexcianBurriotBowlRadioButton);
        ClassicMexcianBurriotBowlRadioButton.setBounds(23, 181, 170, 28);

        BurritoBowlTypeButtonGroup.add(TikkaMasalaBurriotBowlRadioButton);
        TikkaMasalaBurriotBowlRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        TikkaMasalaBurriotBowlRadioButton.setText("Tikka Masala");
        TikkaMasalaBurriotBowlRadioButton.setToolTipText("Creamy Masala sauce, Broccoli, Brown Rice");
        BurritosBowlsPannel.add(TikkaMasalaBurriotBowlRadioButton);
        TikkaMasalaBurriotBowlRadioButton.setBounds(23, 141, 140, 28);

        BurritoBowlTypeButtonGroup.add(BurriotBowlTeriyakiRadioButton);
        BurriotBowlTeriyakiRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        BurriotBowlTeriyakiRadioButton.setText("Teriyaki");
        BurriotBowlTeriyakiRadioButton.setToolTipText("Sweet Teriyaki Sauce, Caramelized Onions, Broccoli, Carrots, Brown Rice");
        BurritosBowlsPannel.add(BurriotBowlTeriyakiRadioButton);
        BurriotBowlTeriyakiRadioButton.setBounds(23, 103, 96, 28);

        BurritoBowlTypeButtonGroup.add(BurritoBowlBuffaloRadioButton);
        BurritoBowlBuffaloRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        BurritoBowlBuffaloRadioButton.setText("Buffalo");
        BurritoBowlBuffaloRadioButton.setToolTipText("Spicy Buffalo Sauce, Blue Cheese Dressing, Celery, Boloco Rice");
        BurritosBowlsPannel.add(BurritoBowlBuffaloRadioButton);
        BurritoBowlBuffaloRadioButton.setBounds(23, 69, 95, 28);

        BurritoBowlFillWithButtonGroup.add(FillWithFreshFajitaVegetablesRadioButton);
        FillWithFreshFajitaVegetablesRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        FillWithFreshFajitaVegetablesRadioButton.setText("Fresh Fajita Vegetables");
        FillWithFreshFajitaVegetablesRadioButton.setToolTipText("Fresh Fajita Vegetables");
        BurritosBowlsPannel.add(FillWithFreshFajitaVegetablesRadioButton);
        FillWithFreshFajitaVegetablesRadioButton.setBounds(236, 249, 241, 28);

        BurritoBowlFillWithButtonGroup.add(FillWithPorkCarnitasRadioButton);
        FillWithPorkCarnitasRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        FillWithPorkCarnitasRadioButton.setText("Pork Carnitas");
        FillWithPorkCarnitasRadioButton.setToolTipText("Pork Carnitas");
        BurritosBowlsPannel.add(FillWithPorkCarnitasRadioButton);
        FillWithPorkCarnitasRadioButton.setBounds(236, 181, 148, 28);

        BurritoBowlFillWithButtonGroup.add(FillWithGrassFedSteakRadioButton);
        FillWithGrassFedSteakRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        FillWithGrassFedSteakRadioButton.setText("Grass Fed Steak");
        FillWithGrassFedSteakRadioButton.setToolTipText("Grass Fed Steak");
        BurritosBowlsPannel.add(FillWithGrassFedSteakRadioButton);
        FillWithGrassFedSteakRadioButton.setBounds(236, 141, 169, 28);

        BurritoBowlFillWithButtonGroup.add(FillWithWhiteMeatChickenRadioButton);
        FillWithWhiteMeatChickenRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        FillWithWhiteMeatChickenRadioButton.setText("White Meat Chicken");
        FillWithWhiteMeatChickenRadioButton.setToolTipText("White Meat Chicken");
        BurritosBowlsPannel.add(FillWithWhiteMeatChickenRadioButton);
        FillWithWhiteMeatChickenRadioButton.setBounds(236, 107, 212, 28);

        BurritoBowlFillWithButtonGroup.add(FillWithDarkMeatChickenRadioButton);
        FillWithDarkMeatChickenRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        FillWithDarkMeatChickenRadioButton.setText("Dark Meat Chicken");
        FillWithDarkMeatChickenRadioButton.setToolTipText("Dark Meat Chicken");
        FillWithDarkMeatChickenRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillWithDarkMeatChickenRadioButtonActionPerformed(evt);
            }
        });
        BurritosBowlsPannel.add(FillWithDarkMeatChickenRadioButton);
        FillWithDarkMeatChickenRadioButton.setBounds(236, 72, 198, 28);

        BurritoBowlFillWithButtonGroup.add(FillWithOrganicTofuRadioButton);
        FillWithOrganicTofuRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        FillWithOrganicTofuRadioButton.setText("Organic Tofu");
        FillWithOrganicTofuRadioButton.setToolTipText("Organic Tofu");
        BurritosBowlsPannel.add(FillWithOrganicTofuRadioButton);
        FillWithOrganicTofuRadioButton.setBounds(236, 215, 147, 28);

        GuacExtraSourCreamCheckbox.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        GuacExtraSourCreamCheckbox.setText("Guac");
        GuacExtraSourCreamCheckbox.setToolTipText("Guac");
        BurritosBowlsPannel.add(GuacExtraSourCreamCheckbox);
        GuacExtraSourCreamCheckbox.setBounds(710, 100, 71, 28);

        SourCreamExtraCheckBox.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        SourCreamExtraCheckBox.setText("Sour Cream");
        SourCreamExtraCheckBox.setToolTipText("Sour Cream");
        BurritosBowlsPannel.add(SourCreamExtraCheckBox);
        SourCreamExtraCheckBox.setBounds(710, 70, 133, 28);

        BurrioBowlSizeComboBox.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        BurrioBowlSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Big Bowl ($8.99)", "Original ($6.79)", "Small ($5.79)", "Mini ($4.49)", "Mini Bundle ($6.79)" }));
        BurrioBowlSizeComboBox.setToolTipText("Size");
        BurritosBowlsPannel.add(BurrioBowlSizeComboBox);
        BurrioBowlSizeComboBox.setBounds(489, 69, 200, 34);

        MenuItemsTabbedPannel.addTab("Burritos/Bowls", BurritosBowlsPannel);

        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Type");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(59, 24, 50, 29);

        SaladTypeButtonGroup.add(CesarSaladRadioButton);
        CesarSaladRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        CesarSaladRadioButton.setText("Cesar");
        CesarSaladRadioButton.setToolTipText("Romaine Lettuce, Herb Croutons, Feta Cheese, Cesar Dressing");
        CesarSaladRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CesarSaladRadioButtonActionPerformed(evt);
            }
        });
        jPanel2.add(CesarSaladRadioButton);
        CesarSaladRadioButton.setBounds(59, 59, 76, 28);

        SaladTypeButtonGroup.add(MedeteranianSaladRadioButton);
        MedeteranianSaladRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        MedeteranianSaladRadioButton.setText("Medeteranian");
        MedeteranianSaladRadioButton.setToolTipText("Romain Lettuce, Black Bean Hummus, Tomato Salsa, Katamala olives, Feta Cheese, Cucumbers, Balsamic Vinaigrette");
        jPanel2.add(MedeteranianSaladRadioButton);
        MedeteranianSaladRadioButton.setBounds(59, 93, 155, 28);

        SaladTypeButtonGroup.add(NewEnglandHarvestSaladRadioButton);
        NewEnglandHarvestSaladRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        NewEnglandHarvestSaladRadioButton.setText("New England Harvest");
        NewEnglandHarvestSaladRadioButton.setToolTipText("Baby Kale, Quinoa, Mushrooms, Squash with Cranberries, Beets, Goat Cheese, Balsamic Vinaigrette");
        jPanel2.add(NewEnglandHarvestSaladRadioButton);
        NewEnglandHarvestSaladRadioButton.setBounds(59, 127, 222, 28);

        SaladTypeButtonGroup.add(CharredBroccoliSaladRadioButton);
        CharredBroccoliSaladRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        CharredBroccoliSaladRadioButton.setText("Charred Broccoli");
        CharredBroccoliSaladRadioButton.setToolTipText("Romaine Lettuce, Faro, Goat Cheese, Pickled Onions, Sunflower Seeds, Balsamic Vinaigrette");
        jPanel2.add(CharredBroccoliSaladRadioButton);
        CharredBroccoliSaladRadioButton.setBounds(59, 161, 181, 28);

        MenuItemsTabbedPannel.addTab("Salads", jPanel2);

        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Type");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(49, 12, 50, 29);

        ShakeTypeButtonGroup.add(NutellaMilkshakeShakeRadioButton);
        NutellaMilkshakeShakeRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        NutellaMilkshakeShakeRadioButton.setText("Nutella Milkshake");
        NutellaMilkshakeShakeRadioButton.setToolTipText("Creamy Nutella, Skim Milk, Non-Fat Frozen Yogurt");
        jPanel3.add(NutellaMilkshakeShakeRadioButton);
        NutellaMilkshakeShakeRadioButton.setBounds(49, 47, 191, 28);

        ShakeTypeButtonGroup.add(JimmyCarterShakeRadioButton);
        JimmyCarterShakeRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        JimmyCarterShakeRadioButton.setText("Jimmy Carter Shake");
        JimmyCarterShakeRadioButton.setToolTipText("All Natural Creamy Peanut Butter, Bananas, Skim Milk, Non-Fat Yogurt");
        jPanel3.add(JimmyCarterShakeRadioButton);
        JimmyCarterShakeRadioButton.setBounds(49, 81, 208, 28);

        ShakeTypeButtonGroup.add(SoyBerryShakeRadioButton);
        SoyBerryShakeRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        SoyBerryShakeRadioButton.setText("Soy Berry Shake");
        SoyBerryShakeRadioButton.setToolTipText("Strawberries, Blueberries, Banana, Soymilk, Honey");
        jPanel3.add(SoyBerryShakeRadioButton);
        SoyBerryShakeRadioButton.setBounds(49, 115, 171, 28);

        ShakeTypeButtonGroup.add(TheMilkshakeRadioButton);
        TheMilkshakeRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        TheMilkshakeRadioButton.setText("The Milkshake");
        TheMilkshakeRadioButton.setToolTipText("Skim Milk, Non-Fat Frozen Yogurt, Choice of 2 Fruits, Vanilla or Chocolate");
        jPanel3.add(TheMilkshakeRadioButton);
        TheMilkshakeRadioButton.setBounds(49, 149, 156, 28);

        ShakeTypeButtonGroup.add(TropiKaleShakeRadioButton);
        TropiKaleShakeRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        TropiKaleShakeRadioButton.setText("Tropi-Kale");
        TropiKaleShakeRadioButton.setToolTipText("Kale, Mango, Cucumbers, Celery, Apple Juice, Honey");
        jPanel3.add(TropiKaleShakeRadioButton);
        TropiKaleShakeRadioButton.setBounds(49, 183, 121, 28);

        ShakeTypeButtonGroup.add(StrawbanaShakeRadioButton);
        StrawbanaShakeRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        StrawbanaShakeRadioButton.setText("Strawbana");
        StrawbanaShakeRadioButton.setToolTipText("Strawberries, Banana, Apple Juice, Orange Juice, Non-Fat Frozen Yogurt");
        jPanel3.add(StrawbanaShakeRadioButton);
        StrawbanaShakeRadioButton.setBounds(49, 217, 122, 28);

        ShakeTypeButtonGroup.add(BerryBlitzShakeRadioButton);
        BerryBlitzShakeRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        BerryBlitzShakeRadioButton.setText("Berry Blitz");
        BerryBlitzShakeRadioButton.setToolTipText("Blueberries, Banana, Apple Juice, Raspberry Sorbet");
        BerryBlitzShakeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerryBlitzShakeRadioButtonActionPerformed(evt);
            }
        });
        jPanel3.add(BerryBlitzShakeRadioButton);
        BerryBlitzShakeRadioButton.setBounds(49, 251, 122, 28);

        ShakeTypeButtonGroup.add(MangoPassionShakeRadioButton);
        MangoPassionShakeRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        MangoPassionShakeRadioButton.setText("Mango Passion");
        MangoPassionShakeRadioButton.setToolTipText("Mango, Mango Juice, Non-Fat Frozen Yogurt");
        jPanel3.add(MangoPassionShakeRadioButton);
        MangoPassionShakeRadioButton.setBounds(49, 285, 165, 28);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setText("Size");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(302, 12, 43, 29);

        SizeShakeComboBox.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        SizeShakeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Original", "Small", "Mini" }));
        SizeShakeComboBox.setToolTipText("ShakeSize");
        jPanel3.add(SizeShakeComboBox);
        SizeShakeComboBox.setBounds(300, 50, 120, 34);

        MenuItemsTabbedPannel.addTab("Shakes", jPanel3);

        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel8.setText("Sides");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(76, 12, 57, 29);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel9.setText("Dessert");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(359, 12, 84, 29);

        OtherSidesButtonGroup.add(ChipsAndGuacSideRadioButton);
        ChipsAndGuacSideRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        ChipsAndGuacSideRadioButton.setText("Chips and Guac");
        ChipsAndGuacSideRadioButton.setToolTipText("ChipsAndGuac");
        jPanel4.add(ChipsAndGuacSideRadioButton);
        ChipsAndGuacSideRadioButton.setBounds(76, 47, 166, 28);

        OtherSidesButtonGroup.add(ChipsAndSalsaSideRadioButton);
        ChipsAndSalsaSideRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        ChipsAndSalsaSideRadioButton.setText("Chips and Salsa");
        ChipsAndSalsaSideRadioButton.setToolTipText("ChipsAndSalsa");
        jPanel4.add(ChipsAndSalsaSideRadioButton);
        ChipsAndSalsaSideRadioButton.setBounds(76, 81, 167, 28);

        OtherSidesButtonGroup.add(ChipsSideRadioButton);
        ChipsSideRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        ChipsSideRadioButton.setText("Chips");
        ChipsSideRadioButton.setToolTipText("Chips");
        jPanel4.add(ChipsSideRadioButton);
        ChipsSideRadioButton.setBounds(76, 115, 77, 28);

        OtherDessertButtonGroup.add(CookieDessertRadioButton);
        CookieDessertRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        CookieDessertRadioButton.setText("Cookie");
        CookieDessertRadioButton.setToolTipText("Cookie");
        jPanel4.add(CookieDessertRadioButton);
        CookieDessertRadioButton.setBounds(359, 47, 89, 28);

        OtherDessertButtonGroup.add(MiniCookieDessertRadioButton);
        MiniCookieDessertRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        MiniCookieDessertRadioButton.setText("Mini Cookie");
        MiniCookieDessertRadioButton.setToolTipText("MiniCookie");
        jPanel4.add(MiniCookieDessertRadioButton);
        MiniCookieDessertRadioButton.setBounds(359, 81, 136, 28);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel10.setText("Dessert");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(359, 12, 84, 29);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel11.setText("Drink");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(581, 12, 59, 29);

        OtherDrinkButtonGroup.add(CoffeeDrinkRadioButton);
        CoffeeDrinkRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        CoffeeDrinkRadioButton.setText("Coffee");
        CoffeeDrinkRadioButton.setToolTipText("Coffee");
        CoffeeDrinkRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffeeDrinkRadioButtonActionPerformed(evt);
            }
        });
        jPanel4.add(CoffeeDrinkRadioButton);
        CoffeeDrinkRadioButton.setBounds(581, 47, 88, 28);

        OtherDrinkButtonGroup.add(SodaDrinkRadioButton);
        SodaDrinkRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        SodaDrinkRadioButton.setText("Soda");
        SodaDrinkRadioButton.setToolTipText("Soda");
        jPanel4.add(SodaDrinkRadioButton);
        SodaDrinkRadioButton.setBounds(581, 81, 71, 28);

        MenuItemsTabbedPannel.addTab("Other", jPanel4);

        getContentPane().add(MenuItemsTabbedPannel);
        MenuItemsTabbedPannel.setBounds(20, 20, 850, 427);

        BolocoImageLabel.setIcon(new javax.swing.ImageIcon("/home/nathan/Pictures/Boloco-logo.gif")); // NOI18N
        BolocoImageLabel.setToolTipText("Boloco");
        getContentPane().add(BolocoImageLabel);
        BolocoImageLabel.setBounds(680, 460, 150, 80);

        RecepitCheckBox.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        RecepitCheckBox.setText("Receipt");
        RecepitCheckBox.setToolTipText("Recepit");
        RecepitCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecepitCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(RecepitCheckBox);
        RecepitCheckBox.setBounds(530, 460, 120, 24);

        AddTipCheckBox.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        AddTipCheckBox.setText("Add 10% Tip");
        AddTipCheckBox.setToolTipText("Add 10% Tip");
        AddTipCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTipCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(AddTipCheckBox);
        AddTipCheckBox.setBounds(530, 490, 150, 24);

        HowManyLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        HowManyLabel.setText("How Many: ");
        getContentPane().add(HowManyLabel);
        HowManyLabel.setBounds(20, 470, 110, 24);

        HowManyTextField.setText("1");
        getContentPane().add(HowManyTextField);
        HowManyTextField.setBounds(130, 470, 86, 28);

        OrderNowButton.setIcon(new javax.swing.ImageIcon("/home/nathan/Pictures/Order-Now.png")); // NOI18N
        OrderNowButton.setToolTipText("Order Now");
        getContentPane().add(OrderNowButton);
        OrderNowButton.setBounds(230, 470, 190, 80);

        RestartButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        RestartButton.setText("Restart");
        RestartButton.setToolTipText("Restart");
        getContentPane().add(RestartButton);
        RestartButton.setBounds(430, 470, 90, 50);

        FileMenu.setText("File");

        NewMenuItem.setText("New");
        NewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(NewMenuItem);

        OpenMenuItem.setText("Open");
        FileMenu.add(OpenMenuItem);

        SaveMenuItem.setText("Save");
        FileMenu.add(SaveMenuItem);

        QuitMenuItem.setText("Quit");
        FileMenu.add(QuitMenuItem);

        jMenuBar1.add(FileMenu);

        EditMenu.setText("Edit");

        SettingsMenuItem.setText("Settings");
        SettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsMenuItemActionPerformed(evt);
            }
        });
        EditMenu.add(SettingsMenuItem);

        jMenuBar1.add(EditMenu);

        HelpMenu.setText("Help");

        AboutMenuItem.setText("About");
        HelpMenu.add(AboutMenuItem);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewMenuItemActionPerformed

    private void FillWithDarkMeatChickenRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillWithDarkMeatChickenRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FillWithDarkMeatChickenRadioButtonActionPerformed

    private void CoffeeDrinkRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffeeDrinkRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoffeeDrinkRadioButtonActionPerformed

    private void RecepitCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecepitCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecepitCheckBoxActionPerformed

    private void AddTipCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTipCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTipCheckBoxActionPerformed

    private void ClassicMexcianBurriotBowlRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassicMexcianBurriotBowlRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassicMexcianBurriotBowlRadioButtonActionPerformed

    private void TheSummerBurrioBowlRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheSummerBurrioBowlRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheSummerBurrioBowlRadioButtonActionPerformed

    private void CesarSaladRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CesarSaladRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CesarSaladRadioButtonActionPerformed

    private void BerryBlitzShakeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerryBlitzShakeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BerryBlitzShakeRadioButtonActionPerformed

    private void SettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BolocoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BolocoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BolocoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BolocoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BolocoMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JCheckBox AddTipCheckBox;
    private javax.swing.JRadioButton BerryBlitzShakeRadioButton;
    private javax.swing.JLabel BolocoImageLabel;
    private javax.swing.JComboBox BurrioBowlSizeComboBox;
    private javax.swing.JRadioButton BurriotBowlTeriyakiRadioButton;
    private javax.swing.JRadioButton BurritoBowlBuffaloRadioButton;
    private javax.swing.ButtonGroup BurritoBowlExtraButtonGroup;
    private javax.swing.ButtonGroup BurritoBowlFillWithButtonGroup;
    private javax.swing.ButtonGroup BurritoBowlSizeButtonGroup;
    private javax.swing.ButtonGroup BurritoBowlTypeButtonGroup;
    private javax.swing.JPanel BurritosBowlsPannel;
    private javax.swing.JRadioButton CesarSaladRadioButton;
    private javax.swing.JRadioButton CharredBroccoliSaladRadioButton;
    private javax.swing.JRadioButton ChipsAndGuacSideRadioButton;
    private javax.swing.JRadioButton ChipsAndSalsaSideRadioButton;
    private javax.swing.JRadioButton ChipsSideRadioButton;
    private javax.swing.JRadioButton ClassicMexcianBurriotBowlRadioButton;
    private javax.swing.JRadioButton CoffeeDrinkRadioButton;
    private javax.swing.JRadioButton CookieDessertRadioButton;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JRadioButton FillWithDarkMeatChickenRadioButton;
    private javax.swing.JRadioButton FillWithFreshFajitaVegetablesRadioButton;
    private javax.swing.JRadioButton FillWithGrassFedSteakRadioButton;
    private javax.swing.JRadioButton FillWithOrganicTofuRadioButton;
    private javax.swing.JRadioButton FillWithPorkCarnitasRadioButton;
    private javax.swing.JRadioButton FillWithWhiteMeatChickenRadioButton;
    private javax.swing.JRadioButton GolocoBurrioBowlRadioButton;
    private javax.swing.JCheckBox GuacExtraSourCreamCheckbox;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JLabel HowManyLabel;
    private javax.swing.JTextField HowManyTextField;
    private javax.swing.JRadioButton JakunBurriotBowlRadioButton;
    private javax.swing.JRadioButton JimmyCarterShakeRadioButton;
    private javax.swing.JRadioButton MangoPassionShakeRadioButton;
    private javax.swing.JRadioButton MedeteranianSaladRadioButton;
    private javax.swing.JTabbedPane MenuItemsTabbedPannel;
    private javax.swing.JRadioButton MiniCookieDessertRadioButton;
    private javax.swing.JRadioButton NewEnglandHarvestSaladRadioButton;
    private javax.swing.JMenuItem NewMenuItem;
    private javax.swing.JRadioButton NutellaMilkshakeShakeRadioButton;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.JButton OrderNowButton;
    private javax.swing.ButtonGroup OtherDessertButtonGroup;
    private javax.swing.ButtonGroup OtherDrinkButtonGroup;
    private javax.swing.ButtonGroup OtherSidesButtonGroup;
    private javax.swing.JMenuItem QuitMenuItem;
    private javax.swing.JCheckBox RecepitCheckBox;
    private javax.swing.JButton RestartButton;
    private javax.swing.ButtonGroup SaladTypeButtonGroup;
    private javax.swing.JMenuItem SaveMenuItem;
    private javax.swing.JMenuItem SettingsMenuItem;
    private javax.swing.ButtonGroup ShakeSizeButtonGroup;
    private javax.swing.ButtonGroup ShakeTypeButtonGroup;
    private javax.swing.JComboBox SizeShakeComboBox;
    private javax.swing.JRadioButton SodaDrinkRadioButton;
    private javax.swing.JCheckBox SourCreamExtraCheckBox;
    private javax.swing.JRadioButton SoyBerryShakeRadioButton;
    private javax.swing.JRadioButton StrawbanaShakeRadioButton;
    private javax.swing.JRadioButton TheMilkshakeRadioButton;
    private javax.swing.JRadioButton TheSummerBurrioBowlRadioButton;
    private javax.swing.JRadioButton TikkaMasalaBurriotBowlRadioButton;
    private javax.swing.JRadioButton TropiKaleShakeRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
