/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nathan
 */
public class OrderingWindow extends javax.swing.JFrame {

    /**
     * Creates new form OrderingWindow
     */
    public OrderingWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        BurritoBowlTypeButtonGroup = new javax.swing.ButtonGroup();
        BurritoBowlFillWithButtonGroup = new javax.swing.ButtonGroup();
        BurritoBowlSizeButtonGroup = new javax.swing.ButtonGroup();
        BurritoBowlExtraButtonGroup = new javax.swing.ButtonGroup();
        SaladTypeButtonGroup = new javax.swing.ButtonGroup();
        ShakeTypeButtonGroup = new javax.swing.ButtonGroup();
        ShakeSizeButtonGroup = new javax.swing.ButtonGroup();
        OtherSidesButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        BurritosBowlsPannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BurritosBowlsPannel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Type");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Extra");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Fill With");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setText("Size");

        BurritoBowlTypeButtonGroup.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton7.setText("Goloco");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, BurritosBowlsPannel, org.jdesktop.beansbinding.ELProperty.create("${}"), jRadioButton7, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        BurritoBowlTypeButtonGroup.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton6.setText("The Summer");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, BurritosBowlsPannel, org.jdesktop.beansbinding.ELProperty.create("${}"), jRadioButton6, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        BurritoBowlTypeButtonGroup.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton5.setText("Cajun");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, BurritosBowlsPannel, org.jdesktop.beansbinding.ELProperty.create("${}"), jRadioButton5, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        BurritoBowlTypeButtonGroup.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton4.setText("Classic Mexican");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, BurritosBowlsPannel, org.jdesktop.beansbinding.ELProperty.create("${}"), jRadioButton4, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        BurritoBowlTypeButtonGroup.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton3.setText("Tikka Masala");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, BurritosBowlsPannel, org.jdesktop.beansbinding.ELProperty.create("${}"), jRadioButton3, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        BurritoBowlTypeButtonGroup.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton2.setText("Teriyaki");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, BurritosBowlsPannel, org.jdesktop.beansbinding.ELProperty.create("${}"), jRadioButton2, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        BurritoBowlTypeButtonGroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton1.setText("Buffalo");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, BurritosBowlsPannel, org.jdesktop.beansbinding.ELProperty.create("${}"), jRadioButton1, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        BurritoBowlFillWithButtonGroup.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton12.setText("Fresh Fajita Vegetables");

        BurritoBowlFillWithButtonGroup.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton11.setText("Pork Carnitas");

        BurritoBowlFillWithButtonGroup.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton10.setText("Grass Fed Steak");

        BurritoBowlFillWithButtonGroup.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton9.setText("White Meat Chicken");

        BurritoBowlFillWithButtonGroup.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton8.setText("Dark Meat Chicken");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        BurritoBowlSizeButtonGroup.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton18.setText("Big Bowl");

        BurritoBowlSizeButtonGroup.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton19.setText("Original");

        BurritoBowlSizeButtonGroup.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton20.setText("Small");

        BurritoBowlSizeButtonGroup.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton21.setText("Mini");

        BurritoBowlSizeButtonGroup.add(jRadioButton22);
        jRadioButton22.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton22.setText("Mini Bundle");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });

        BurritoBowlExtraButtonGroup.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton13.setText("Sour Cream");

        BurritoBowlExtraButtonGroup.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton14.setText("Guac");

        BurritoBowlFillWithButtonGroup.add(jRadioButton40);
        jRadioButton40.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton40.setText("Organic Tofu");

        javax.swing.GroupLayout BurritosBowlsPannelLayout = new javax.swing.GroupLayout(BurritosBowlsPannel);
        BurritosBowlsPannel.setLayout(BurritosBowlsPannelLayout);
        BurritosBowlsPannelLayout.setHorizontalGroup(
            BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BurritosBowlsPannelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addGap(43, 43, 43)
                .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton12)
                    .addGroup(BurritosBowlsPannelLayout.createSequentialGroup()
                        .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton21)
                            .addComponent(jRadioButton22)
                            .addGroup(BurritosBowlsPannelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(107, 107, 107)
                                .addComponent(jLabel2))
                            .addGroup(BurritosBowlsPannelLayout.createSequentialGroup()
                                .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton18)
                                    .addComponent(jRadioButton19)
                                    .addComponent(jRadioButton20))
                                .addGap(42, 42, 42)
                                .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton13)
                                    .addComponent(jRadioButton14))))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        BurritosBowlsPannelLayout.setVerticalGroup(
            BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BurritosBowlsPannelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BurritosBowlsPannelLayout.createSequentialGroup()
                        .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton18)
                            .addComponent(jRadioButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton19)
                            .addComponent(jRadioButton14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton22))
                    .addGroup(BurritosBowlsPannelLayout.createSequentialGroup()
                        .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BurritosBowlsPannelLayout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5))
                            .addGroup(BurritosBowlsPannelLayout.createSequentialGroup()
                                .addComponent(jRadioButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton40)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BurritosBowlsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton7)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Burritos/Bowls", BurritosBowlsPannel);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Type");

        SaladTypeButtonGroup.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton15.setText("Cesar");

        SaladTypeButtonGroup.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton16.setText("Medeteranian");

        SaladTypeButtonGroup.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton17.setText("New England Harvest");

        SaladTypeButtonGroup.add(jRadioButton23);
        jRadioButton23.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton23.setText("Charred Broccoli");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton15)
                    .addComponent(jLabel5))
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton23)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salads", jPanel2);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Type");

        ShakeTypeButtonGroup.add(jRadioButton24);
        jRadioButton24.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton24.setText("Nutella Milkshake");

        ShakeTypeButtonGroup.add(jRadioButton25);
        jRadioButton25.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton25.setText("Jimmy Carter Shake");

        ShakeTypeButtonGroup.add(jRadioButton26);
        jRadioButton26.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton26.setText("Soy Berry Shake");

        ShakeTypeButtonGroup.add(jRadioButton27);
        jRadioButton27.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton27.setText("The Milkshake");

        ShakeTypeButtonGroup.add(jRadioButton28);
        jRadioButton28.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton28.setText("Tropi-Kale");

        ShakeTypeButtonGroup.add(jRadioButton29);
        jRadioButton29.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton29.setText("Strawbana");

        ShakeTypeButtonGroup.add(jRadioButton30);
        jRadioButton30.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton30.setText("Berry Blitz");

        ShakeTypeButtonGroup.add(jRadioButton31);
        jRadioButton31.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton31.setText("Mango Passion");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setText("Size");

        ShakeSizeButtonGroup.add(jRadioButton32);
        jRadioButton32.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton32.setText("Original");

        ShakeSizeButtonGroup.add(jRadioButton33);
        jRadioButton33.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton33.setText("Small");

        ShakeSizeButtonGroup.add(jRadioButton34);
        jRadioButton34.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton34.setText("Mini");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton31)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton28)
                    .addComponent(jRadioButton27)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton24)
                            .addComponent(jRadioButton25)
                            .addComponent(jRadioButton26))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton34)
                            .addComponent(jRadioButton33)
                            .addComponent(jRadioButton32)
                            .addComponent(jLabel7))))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton25)
                    .addComponent(jRadioButton33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton31)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Shakes", jPanel3);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel8.setText("Sides");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel9.setText("Dessert");

        jRadioButton35.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton35.setText("Chips and Guac");

        jRadioButton36.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton36.setText("Chips and Salsa");

        jRadioButton37.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton37.setText("Chips");

        jRadioButton38.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton38.setText("Cookie");

        jRadioButton39.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton39.setText("Mini Cookie");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton37)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jRadioButton35)
                            .addComponent(jRadioButton36))
                        .addGap(116, 116, 116)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton39)
                            .addComponent(jRadioButton38)
                            .addComponent(jLabel9))))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton35)
                    .addComponent(jRadioButton38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton36)
                    .addComponent(jRadioButton39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton37)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Other", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(12, 12, 828, 427);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BurritoBowlExtraButtonGroup;
    private javax.swing.ButtonGroup BurritoBowlFillWithButtonGroup;
    private javax.swing.ButtonGroup BurritoBowlSizeButtonGroup;
    private javax.swing.ButtonGroup BurritoBowlTypeButtonGroup;
    private javax.swing.JPanel BurritosBowlsPannel;
    private javax.swing.ButtonGroup OtherSidesButtonGroup;
    private javax.swing.ButtonGroup SaladTypeButtonGroup;
    private javax.swing.ButtonGroup ShakeSizeButtonGroup;
    private javax.swing.ButtonGroup ShakeTypeButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
